### ISSUE TITLE
Upgrading the version to the latest

### ISSUE THREAD

**Issue by msaiyaff** [spirosikmd/angular2-focus#26]
Since the version has upgraded to version 4 upgrading the application to angular v4 might help the community

**Comment by spirosikmd** [comment]
Hi @msaiyaff! I've already updated it to use angular v4, check the [package.json](https://github.com/spirosikmd/angular2-focus/blob/master/package.json#L30). Maybe you tried it and something is not working? Thanks!

**Comment by msaiyaff** [comment]
My bad. Couldn't have a look at it. Unfortunately, when I integrated this with the app, this was not working. I am trying to focus an input field in a modal, when a modal pops up.
Any clue?

**Comment by spirosikmd** [comment]
Thank you for the extra information! Can you please provide an example so I can reproduce it? Otherwise, I could try myself?

**Comment by spirosikmd** [comment]
@msaiyaff have you used any kind of modal library? I can then try reproducing the issue using the same library? Thanks!

**Comment by msaiyaff** [comment]
Sorry for hanging a bit @spirosikmd 
Just using it with bootstrap modal. 😄 
I'll just add a snippet or some code and share the link here? Might need some time though

**Comment by spirosikmd** [comment]
Thanks @msaiyaff! I would much appreciate it! I can give it a try as well. Are you using a specific library for boostrap modal?

**Comment by spirosikmd** [comment]
@msaiyaff #32 implements an example using [angular bootstrap modal](https://ng-bootstrap.github.io/#/components/modal). The input element is focused when modal is opened. Everything seems to work. Are you trying to implement something like this? Is your case more complex? Thanks!
