### ISSUE TITLE
ng 4 + this library wont execute

### ISSUE THREAD

**Issue by geetee24** [spirosikmd/angular2-focus#41]
get Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'. Please add a @NgModule annotation.

indeed in my app.module.ts, I have 
import { FocusModule } from 'angular2-focus';						

imports....
		FocusModule.forRoot()

Can you advise?

**Comment by spirosikmd** [comment]
Hi @geetee24! Thank you for submitting this issue. Currently, the project supports angular 4.1.2. I updated to latest angular 4.4.1 in #45 and it still works. Can you provide a sample app that reproduces this issue? Thanks!

**Comment by spirosikmd** [comment]
Hi @geetee24! I am closing this issue. I assume latest version fixed your issue. Please feel free to reopen it if this is not the case!
