### ISSUE TITLE
Getting an error of a badly packaged library, after upgrading to angular 5

### ISSUE THREAD

**Issue by dizhar** [spirosikmd/angular2-focus#71]
ERROR in ./node_modules/angular2-focus/src/focus.module.ts
Module build failed: Error: C:\loltlv\node_modules\angular2-focus\src\focus.module.ts is missing from the TypeScript compilation. Please make sure it is in
 your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an is
sue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\loltlv\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (C:\loltlv\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
ERROR in ./node_modules/ng2-file-drop/index.ts
Module build failed: Error: C:\loltlv\node_modules\ng2-file-drop\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconf
ig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an is
sue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\loltlv\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (C:\loltlv\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by spirosikmd** [comment]
Hi @dizhar! Which version of `angular2-focus` are you using? The [latest version](https://github.com/spirosikmd/angular2-focus/releases/tag/v1.1.2) should have fixed the support for angular 5.

**Comment by spirosikmd** [comment]
I assume that it works for you @dizhar? I am closing this issue. Please feel free to reopen it in case it doesn't work.

**Comment by dizhar** [comment]
Yes, you fixed the issue. Thank you. Great package. I love using it.
