### ISSUE TITLE
Reset focus not working

### ISSUE THREAD

**Issue by TwunTee** [spirosikmd/angular2-focus#82]
Focus works perfectly fine when enabled at first, if i try to make focus false and then add true again nothing happens but ng-reflect seems to update the state from false to true but the element doesnt not get focused

**To Reproduce**
1.  Make the focus property false initially
2. Make the property true, the element should be focused now
3. Make the property false 
4. Now make it true again

**Expected behavior**
The element should be focused again

**Comment by spirosikmd** [comment]
Hi @TwunTee! Thank you for submitting this issue. I can reproduce it. Commit 15e151a15f introduced this issue. I have an idea about a fix that I will work on the coming days.

**Comment by spirosikmd** [comment]
Hi @TwunTee! Please check if the new version fixes this issue! Thanks!
