### ISSUE TITLE
update to angular 6

### ISSUE THREAD

**Issue by losorio35** [spirosikmd/angular2-focus#86]
hello guys, Do you plan to update this library? to be compatible with angular 6

**Comment by spirosikmd** [comment]
Hi @losorio35! Thank you for submitting this issue! Yes, the plan is to update the library to support angular 6 soon. Just for my understanding, have you tried it with an angular 6 project? Does something break?

**Comment by odahcam** [comment]
Probably you gonna need `rxjs-compat`, as ng 5 and 6 uses different versions of RxJS.

**Comment by spirosikmd** [comment]
Hi @losorio35 and @odahcam! Can you give this branch a try, just to make sure everything works properly? Thanks!
