### ISSUE TITLE
Pressing Enter is invoking incorrect execution

### ISSUE THREAD

**Issue by onlyanup** [spirosikmd/angular2-focus#87]
**Describe the bug**
I have a dynamic form in which controls are generated dynamically. Here is a sample control:
`<mat-form-field class="form-field" [hintLabel]="formEditorModel.hint">`
`<mat-label>{{formEditorModel.label}}</mat-label>`         
`<input matInput type="text" autocomplete="off" focus="{{formEditorModel.autoFocus}}"               placeholder="{{formEditorModel.placeHolder}}" formControlName="{{formEditorModel.key}}" [required]="formEditorModel.required">`
 `<button tabindex="-1" *ngIf="form.controls[formEditorModel.key].value" (click)="form.controls[formEditorModel.key].reset()" matSuffix mat-icon-button aria-label="Clear">
               <mat-icon>close</mat-icon>
</button>`
`<mat-error>{{GetFormError()}}</mat-error>`
`<mat-hint align="end">{{GetHint()}}</mat-hint>`
`</mat-form-field>`

As you can see I have used the angular material here. I have a mat-form-field. Inside that there are usual components like Label, Input, Suffix clear button, Error text and Hint text.

Form has a submit button and a reset/cancel button. Submit button is the default action and works correctly. When the focus directive is not used and we enter data into the control and hit enter, the form is submitted. But when focus is used and we hit enter, the suffix clear button is clicked and the data entered in the control is cleared.

**To Reproduce**
Add the provided mat-form-field in a angular 6 material form.
Enter some data into the input control
Press Enter/return button

Entered text gets cleared.

**Expected behavior**
Not to focus on Any suffix button in mat-form-field when the focus is on the control. So that when we press enter it calls the default form action and not any unwanted things.

**Screenshots**
![image](https://user-images.githubusercontent.com/37064591/43682058-362078c4-9885-11e8-962c-777974a9bf53.png)

**Desktop (please complete the following information):**
 - OS: windows 10 pro
 - Browser Google Chrome
 - Version 67

**Comment by spirosikmd** [comment]
Hey @onlyanup! Thanks for the detailed issue! I will try and reproduce this. I will first work on #86 to make sure everything works with angular 6, then take a look at this again.

**Comment by onlyanup** [comment]
Hey there, My bad. I didn't include the type="button" in the clear button hence the default action was clear the text. You can close this issue.
Sorry for the delayed response though, was clearing my backlogs now.

**Comment by spirosikmd** [comment]
Awesome that it works for you now! Thank you for taking the time to respond!
