### ISSUE TITLE
Can't focus to other elemenets

### ISSUE THREAD

**Issue by tutv95** [spirosikmd/angular2-focus#9]
Hi @spirosikmd,

I used this module and config successful. Then user can't focus other elements! It really is wrong :3
I think that it just should focus the first time 👍 

Regards,
Max

**Comment by spirosikmd** [comment]
Hi @tutv95! Thank you very much for submitting an issue. Unfortunately, I can't replicate it. I would much appreciate it if you provide an example that replicates this issue. Thanks!

**Comment by calhemp** [comment]
Hi, @spirosikmd  sorry to brother, but I've the same issue. I like your work and I would like to use it in my simple project,
works well in a simple test with 2 elements, first element with focus='true'  and second none. and works when load. and can change to other input well, with tab and click

but
when creating a form with 
import { ReactiveFormsModule } from '@angular/forms'; 
and adding the form for example
<input type="text" name="nombre" class="form-control" formControlName="nombre" focus="true"/>
 <input type="text" name="nif" class="form-control" formControlName="nif" />
when loads ,"nombre" gets focus but
in firefox, when change to 'nif' input, always return to "nombre" input with tab or click,
and in chrome, it never changes to 'nif' input. no click no tab, as somehow disabled :(

sorry for my bad example, but I tried to load a plnkr but I can't add your directive in the example, (https://unpkg.com)
or if there is a example online for put a simple demo to try and show you my experience with this

thanks, 
Pere

**Comment by spirosikmd** [comment]
Hi @calhemp! Thank you very much for the extra information. I will try to reproduce the issue using an example with `@angular/forms`.

**Comment by calhemp** [comment]
wow, thanks @spirosikmd .

**Comment by spirosikmd** [comment]
@calhemp @tutv95 this should be fixed now! Please give it another try and let me know! Thanks 🎉

**Comment by calhemp** [comment]
Works Perfect now! ;) many thanks

**Comment by spirosikmd** [comment]
Great to hear! Thank you for contributing to this issue 😃
